version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u131-jdk

    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      # branch version
      BUILD_VERSION: "1.0.0"

      # webapp build flag
      BUILD_WEBAPP: "true"

      # webapp1 build flag
      BUILD_WEBAPP1: "false"

    working_directory: ~/source-all

    branches:
      only:
        - /develop\/.*/

    steps:
      - checkout

      - run: 
          name: webapp-build
          command: |
            if [[ ${BUILD_WEBAPP} = "true" ]];
            then
              mvn -B -f webapp/pom.xml clean package findbugs:findbugs pmd:pmd -Dbuild.number=${CIRCLE_BUILD_NUM} -Pdeploy -Dmaven.test.skip=true;
            else
              echo "skip webapp-build";
            fi

      - run: 
          name: webapp1-build
          command: |
            if [[ ${BUILD_WEBAPP1} = "true" ]];
            then
              mvn -B -f webapp1/pom.xml clean package findbugs:findbugs pmd:pmd -Dbuild.number=${CIRCLE_BUILD_NUM} -Pdeploy -Dmaven.test.skip=true;
            else
              echo "skip webapp1-build";
            fi

      - run: 
          name: webapp-copy-war
          command: |
            if [[ ${BUILD_WEBAPP} = "true" ]];
            then
              cp webapp/appExample01/target/appExample01.war webapp/target/;
              cp webapp/appExample02/target/appExample02.war webapp/target/;
            else
              echo "skip webapp-copy-war";
            fi

      - run: 
          name: webapp1-copy-war
          command: |
            if [[ ${BUILD_WEBAPP1} = "true" ]];
            then
              cp webapp1/app1Example01/target/app1Example01.war webapp1/target/;
              cp webapp1/app1Example02/target/app1Example02.war webapp1/target/;
            else
              echo "skip webapp1-copy-war";
            fi

      - deploy:
          command: |
            echo "${BUILD_VERSION} deployment"
            if [[ ${BUILD_WEBAPP} = "true" || ${BUILD_WEBAPP1} = "true" ]];
            then
              git clone https://github.com/public-test-circleci/module-all.git;
              cd module-all;
              git checkout release/${BUILD_VERSION};
            else
              echo "skip command";
            fi
            # webapp deployment
            if [[ ${BUILD_WEBAPP} = "true" ]];
            then
              cp -f ~/${CIRCLE_PROJECT_REPONAME}/webapp/target/*.war webapp/;
            else
              echo "skip command";
            fi
            # webapp1 deployment
            if [[ ${BUILD_WEBAPP1} = "true" ]];
            then
              cp -f ~/${CIRCLE_PROJECT_REPONAME}/webapp1/target/*.war webapp1/;
            else
              echo "skip command";
            fi
            if [[ ${BUILD_WEBAPP} = "true" || ${BUILD_WEBAPP1} = "true" ]];
            then
              git config --global user.email "";
              git config --global user.name ${CIRCLE_USERNAME};
              git commit -am "deploy from CircleCI(Number:${CIRCLE_BUILD_NUM})";
              git push origin release/${BUILD_VERSION};
            else
              echo "skip command";
            fi

# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
